### PR TITLE
Update to DSS C-API 0.10.1

### PR DESCRIPTION
**Pull request by PMeira**
I'll probably release DSS C-API 0.10.1 tomorrow, so I'm making a PR to try to trigger the tests on all platforms. 

I'm also going to check this in older versions of OpenDSS to see if it really changed or what happened:
```
# Value updated as of OpenDSS 7.6.5.86, SVN rev 2463, electricdss-src d867ca306d2448ba03d7bb28699fa4ecec94119c
@test Meters.Totals()[1] ≋ 23830.586235396186
```

### CODE REVIEW

**Comment by PMeira** [comment]
There are further issues with `DoReliabilityCalc` that I didn't notice.  I posted [on the forum](https://sourceforge.net/p/electricdss/discussion/experts/thread/57498b3cea/), but there could be more issues. 

If I'm not able to fully fix it this Monday, I'll revert part of the changes from this PR and handle them some other day.

**Comment by kdheepak** [comment]
Thanks for looking into this!

**Comment by PMeira** [comment]
About this:
```
# Value updated as of OpenDSS 7.6.5.86, SVN rev 2463, electricdss-src d867ca306d2448ba03d7bb28699fa4ecec94119c
@test Meters.Totals()[1] ≋ 23830.586235396186
```
I tested version 7.6.5.20 (from 2016) and it gives the same value. Earlier versions just crash on various issues, even without most of the other calls from the tests.

**Comment by kdheepak** [comment]
When you say 7.6.5.20 (from 2016) do you mean using the official OpenDSS libraries on Windows?

**Comment by PMeira** [comment]
> When you say 7.6.5.20 (from 2016) do you mean using the official OpenDSS libraries on Windows?

Yes, whenever I mention a version in that format (7.6.5.20) it's referencing the version reported from the official COM DLL. I'll try to be more clear about it.

**Comment by kdheepak** [comment]
I figured from the svn rev tag, I just wanted to be sure! This all looks good to me!

**Comment by PMeira** [comment]
@kdheepak Better let the CI finish just to be sure, but we probably want to squash this, right?

**Comment by kdheepak** [comment]
We can wait for @tshort to review as well. I personally would use git interactive rebase in this case and squash it into three or so commits, but I'm fine with using github's squash and merge feature too.

Additionally, I think we should add a function to get the current version of the Julia package, similar to `opendssdirect.__version__` in Python, add another function to get the version of the `dss_capi`, and another function to get the version of opendss used. Maybe the following:

```
function opendssdirect_version()::String
function dsscapi_version()::String
function opendss_version()::String
```

Thoughts? This can also instead be in a separate PR but we should get these in before the next tag.

**Comment by PMeira** [comment]
> I personally would use git interactive rebase in this case and squash it into three or so commits

Ah, sure, I'll do that tomorrow.

> Additionally, I think we should add a function to get the current version (...)

Right now `DSS_Get_Version` returns an ugly blob and doesn't really contain all the useful information:

"DSS C-API Library version 0.10.1 revision 6d02c840b0165dd68f203e869097b3a8ecdb702e based on OpenDSS SVN 2504 (v7/classic variation) (64-bit build); License Status: Open "

We could parse that but I know it's bad. I tried to the same format as the COM DSS.Version but that was a bad idea.

I think a simpler function that returns 0.10.1 is enough for DSS C-API (I always tag electricdss-src with the same version) and another that returns the just the base OpenDSS revision (not sure how easy is to get the Delphi project version) would be much better.

Another issue is that KLUSolve is not listed anywhere yet and it's probably a good idea to do it. I'm decoupling the source code into a new repo soon (https://github.com/dss-extensions/dss_capi/issues/25) as I'm adding some small things into it, so it's better to version it too. The upstream repo for KLUSolve hasn't changed in a few years and it didn't list versions.

**Comment by kdheepak** [comment]
The main reason I think such a string is useful is that when someone posts an issue we can ask them to include that so that it's easier for us to debug the problem. If just the "0.10.1" number will help us know exactly which version of which libraries were used then that is all that's needed. Ideally though I think I'd like to know exactly which commit hash was used for everything, but maybe that's just me :)

**Comment by PMeira** [comment]
> If just the "0.10.1" number will help us know exactly which version of which libraries were used then that is all that's needed.

As long as we keep tagging the releases, it should be (it's not a bad idea to include the short hash in the version though). The full commit hash is included in the current `Basic.Version()`, but my point is that it is not complete -- we would need to now what are the commits or versions for all dependencies -- DSS C-API itself, electricdss-src, KLUSolve, SuiteSparse and Free Pascal itself. I'm contemplating what's the best way to do it in dss_capi. 

For unreleased versions, yeah, we'd need the hashes anyway.

For `opendssdirect_version()`, is there a convention in Julia? Of course it is included in `Project.toml`, but looking in a few packages, I couldn't find a function dedicated for the version. As long as the package is installed, `Pkg.status("OpenDSSDirect")` would be enough. We can provide a plain string too.

For `dss_capi_version()` and `opendss_version()`, we could just process `Basic.Version()` to extract the components(e.g. "0.10.1" and "SVN 2504"), something like:

```julia
"""Returns the OpenDSSDirect.jl version"""
function opendssdirect_version()::String 
    return "0.5.0"
end

"""Returns the DSS C-API library version"""
function dss_capi_version()::String 
    return match(r"DSS C-API Library version ([^\s]+)", Basic.Version())[1]
end

"""Returns the OpenDSS revision used in the DSS C-API"""
function opendss_version()::String
    return match(r"OpenDSS (SVN [^\s]+)", Basic.Version())[1]
end
```

**Comment by kdheepak** [comment]
Is this ready to merge?

**Comment by kdheepak** [comment]
@tshort let us know if you have any comments on this, otherwise @PMeira you can merge this.

**Comment by tshort** [comment]
I don't have any comments...

**Comment by kdheepak** [comment]
@PMeira You can merge this first then. I'll rebase the other open PR on top of the latest master and then merge that one.

**Comment by kdheepak** [comment]
After these are merged, I'd want to tag a new minor release but I think we'd have to wait for https://github.com/JuliaLang/METADATA.jl/pull/21308 to be merged first.

**Comment by PMeira** [comment]
@kdheepak OK, merging. Keep in mind I didn't add the version functions since I wasn't sure what to do.
https://github.com/dss-extensions/OpenDSSDirect.jl/pull/33#issuecomment-463050960
https://github.com/dss-extensions/OpenDSSDirect.jl/pull/33#issuecomment-463472405

**Comment by kdheepak** [comment]
Sounds good, we can add the versions in a separate PR.

**Pull request merged**
