### PR TITLE
Add Enum support

### PR DESCRIPTION
**Pull request by kdheepak**
This PR will make certain functions dispatch only on specific values.

```
julia> using OpenDSSDirect

julia> dss("redirect ./test.dss")
""

julia> Solution.Mode()
SolveModes_SnapShot(0)

julia> Solution.Mode(1)

julia> Solution.Mode()
SolveModes_Daily(1)

julia> Solution.Mode(OpenDSSDirect.Lib.SolveModes_Harmonic)

julia> Solution.Mode()
SolveModes_Harmonic(15)

julia> Solution.Mode(200)
ERROR: ArgumentError: invalid value for Enum SolveModes: 200
Stacktrace:
 [1] enum_argument_error(::Symbol, ::Int64) at ./Enums.jl:29
 [2] convert at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/CEnum.jl:103 [inlined]
 [3] Mode(::Int64) at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/solution.jl:321
 [4] top-level scope at none:0

help?> Solution.Mode
  Mode()::OpenDSSDirect.Lib.SolveModes



  Get present solution mode (by a text code - see DSS Help)

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────

  Mode(Value::Union{Int64, SolveModes})



  Set present solution mode (by a text code - see DSS Help)

julia>
```

### CODE REVIEW

**Comment by kdheepak** [comment]
@PMeira where are [`Options`](https://github.com/dss-extensions/dss_capi/blob/cc9b6d58ff5a83a6084b75d83d2713625c888470/include/v7/dss_capi.h#L5377) used?

**Comment by PMeira** [comment]
> where are [`Options`](https://github.com/dss-extensions/dss_capi/blob/cc9b6d58ff5a83a6084b75d83d2713625c888470/include/v7/dss_capi.h#L5377) used?

@kdheepak That's a mess, it's actually 6 enums merged in one (kept from COM, as usual). 
I'll split it in the master branch and add the missing comments.

**Comment by PMeira** [comment]
@kdheepak There you go:

```c
    enum SolutionLoadModels { // Solution_[Get/Set]_LoadModel
        SolutionLoadModels_PowerFlow = 1, // Power Flow load model option
        SolutionLoadModels_Admittance = 2 // Admittance load model option
    };

    enum SolutionAlgorithms { // Solution_[Get/Set]_Algorithm
        SolutionAlgorithms_NormalSolve = 0, // Solution algorithm option - Normal solution mode
        SolutionAlgorithms_NewtonSolve = 1 // Solution algorithm option - Newton solution
    };

    enum ControlModes { // Solution_[Get/Set]_ControlMode
        ControlModes_Static = 0, // Control Mode option - Static
        ControlModes_Event = 1, // Control Mode Option - Event driven solution mode
        ControlModes_Time = 2, // Control mode option - Time driven mode
        ControlModes_ControlOff = -1 // Control Mode OFF
    };

    enum CktModels { // Settings_[Get/Set]_CktModel
        CktModels_Multiphase = 0, // Circuit model is multiphase (default)
        CktModels_PositiveSeq = 1 // Circuit model is positive sequence model only
    };

    enum RandomModes { // Solution_[Get/Set]_Random
        RandomModes_Gaussian = 1, // Gaussian
        RandomModes_Uniform = 2, // Uniform
        RandomModes_LogNormal = 3 // Log normal
    };

    enum AutoAddTypes { // Solution_[Get/Set]_AddType
        AutoAddTypes_AddGen = 1, // Add generators in AutoAdd mode
        AutoAddTypes_AddCap = 2 // Add capacitors in AutoAdd mode
    };
```

**Comment by kdheepak** [comment]
@PMeira 

```
    enum ControlModes { // Solution_[Get/Set]_ControlMode
        ControlModes_Static = 0,
        ControlModes_Event = 1,
        ControlModes_Time = 2, 
        ControlModes_ControlOff = -1 <-- This is the only value that is negative.
    };
```

The negative value [here](https://github.com/dss-extensions/dss_capi/blob/5e4cff0b740b32172fbc2bfcfd2c3ff30b797e60/include/v7/dss_capi.h#L5377
) is causing an issue in current implementation of `@cenum` macro in Julia. Previously it was [`0xFFFFFFFF`](https://github.com/dss-extensions/dss_capi/blob/cc9b6d58ff5a83a6084b75d83d2713625c888470/include/v7/dss_capi.h#L5392), what are the implications of leaving it the way it was before?

**Comment by kdheepak** [comment]
If I don't load any feeder, the following throw an error because they return a value that is not within the enum.

```

julia> using OpenDSSDirect

julia> Monitors.Mode()
ERROR: ArgumentError: invalid value for Enum MonitorModes: 621098376
Stacktrace:
 [1] enum_argument_error(::Symbol, ::Int32) at ./Enums.jl:29
 [2] convert at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/CEnum.jl:103 [inlined]
 [3] Mode() at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/monitors.jl:108
 [4] top-level scope at none:0

julia> Solution.AddType()
ERROR: ArgumentError: invalid value for Enum AutoAddTypes: 0
Stacktrace:
 [1] enum_argument_error(::Symbol, ::Int32) at ./Enums.jl:29
 [2] convert at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/CEnum.jl:103 [inlined]
 [3] AddType() at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/solution.jl:90
 [4] top-level scope at none:0

julia> Solution.LoadModel()
ERROR: ArgumentError: invalid value for Enum SolutionLoadModels: 0
Stacktrace:
 [1] enum_argument_error(::Symbol, ::Int32) at ./Enums.jl:29
 [2] convert at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/CEnum.jl:103 [inlined]
 [3] LoadModel() at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/solution.jl:263
 [4] top-level scope at none:0

julia> Solution.Random()
ERROR: ArgumentError: invalid value for Enum RandomModes: 0
Stacktrace:
 [1] enum_argument_error(::Symbol, ::Int32) at ./Enums.jl:29
 [2] convert at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/CEnum.jl:103 [inlined]
 [3] Random() at /Users/$USER/GitRepos/OpenDSSDirect.jl/src/solution.jl:356
 [4] top-level scope at none:0

julia>
```

@PMeira It might be worth adding an `Unknown` attribute to all of the `enum` definitions that is set to `0`. 

Additonally, the `Monitors.Mode` function specifically returns a different `Int` value every time I restart a Julia session. There may be something else going on there.

**Comment by kdheepak** [comment]
The tests all pass, I'm going to merge this in.

**Comment by PMeira** [comment]
@kdheepak Unfortunately we can't declare the integral type for enums in C, so I changed all values to decimals to make them more explicit and unambiguous, except the monitors enum since it is used as a bitmask. `0xFFFFFFFF` is -1 as a 32-bit signed integer, so as long as the bit representation is the same, it'd fine.  But testing in Julia 1.1, `ControlModes_ControlOff` doesn't work as CEnum defaults to a UInt32 and that doesn't work with the parameter declared as Int32.

We can provide a value type for cenum though:
```julia
    @cenum(ControlModes{Int32},
        ControlModes_Static = 0,
        ControlModes_Event = 1,
        ControlModes_Time = 2,
        ControlModes_Multirate = 3,
        ControlModes_ControlOff = -1,
    )
```

I haven't used Julia that much yet, do you see any downside to this change? 

Checking to see if the -1 value even matters in the OpenDSS code (it does, there is an equal comparison somewhere), I noticed the enum was missing the value for `ControlModes_Multirate`, added above.

> If I don't load any feeder, the following throw an error because they return a value that is not within the enum.

The right thing to do is probably to raise an error, maybe coupled with a new enum value indicating the call was invalid.

> Additonally, the `Monitors.Mode` function specifically returns a different `Int` value every time I restart a Julia session. There may be something else going on there.

That's without a circuit too, right? It's uninitialized memory. Most OpenDSS functions don't make sense without a circuit or a component of the certain type.  These are trivial to update but most of the code is being rewritten in dss_capi 0.11, so I rather not change it now, and the COM DLL behavior is mostly the same. I should start working more on 0.11 again next week.

**Comment by kdheepak** [comment]
Thanks for checking! I'll submit a new PR for this change.

**Pull request merged**
